spring:
  apprication:
    name: parish
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://146.56.115.236:3306/parish_info
    username: manager
    password: alsrn8746!

logging:
  level:
    root: info
    com.psc: debug